export const CATEGORIES = [
  "Fiction",
  "Non-Fiction",
  "Science",
  "Technology",
  "History",
  "Biography",
  "Fantasy",
  "Mystery",
  "Romance",
  "Self-Help",
];

export const INITIAL_BOOKS = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "978-0743273565",
    price: 15.99,
    description:
      "A story of wealth, love, and the American Dream in the 1920s.",
    coverImage: "https://picsum.photos/seed/gatsby/400/600",
    stockQuantity: 12,
    categories: ["Fiction", "History"],
    publisher: "Scribner",
    publicationDate: "1925-04-10",
    rating: 4.5,
    reviews: [],
  },
  {
    id: "2",
    title: "Clean Code",
    author: "Robert C. Martin",
    isbn: "978-0132350884",
    price: 44.99,
    description: "A handbook of agile software craftsmanship.",
    coverImage: "https://picsum.photos/seed/cleancode/400/600",
    stockQuantity: 5,
    categories: ["Technology", "Science"],
    publisher: "Pearson",
    publicationDate: "2008-08-01",
    rating: 4.8,
    reviews: [],
  },
  {
    id: "3",
    title: "Atomic Habits",
    author: "James Clear",
    isbn: "978-0735211292",
    price: 18,
    description:
      "An easy and proven way to build good habits and break bad ones.",
    coverImage: "https://picsum.photos/seed/habits/400/600",
    stockQuantity: 25,
    categories: ["Self-Help", "Non-Fiction"],
    publisher: "Avery",
    publicationDate: "2018-10-16",
    rating: 4.9,
    reviews: [],
  },
  {
    id: "4",
    title: "Brief Answers to the Big Questions",
    author: "Stephen Hawking",
    isbn: "978-1473695986",
    price: 22.5,
    description: "The final book from the world famous cosmologist.",
    coverImage: "https://picsum.photos/seed/hawking/400/600",
    stockQuantity: 8,
    categories: ["Science", "Non-Fiction"],
    publisher: "Bantam",
    publicationDate: "2018-10-16",
    rating: 4.7,
    reviews: [],
  },
  {
    id: "5",
    title: "1984",
    author: "George Orwell",
    isbn: "978-0451524935",
    price: 13.99,
    description: "A chilling dystopian novel about surveillance and control.",
    coverImage: "https://picsum.photos/seed/1984/400/600",
    stockQuantity: 14,
    categories: ["Fiction", "Science"],
    publisher: "Signet Classic",
    publicationDate: "1949-06-08",
    rating: 4.7,
    reviews: [],
  },
  {
    id: "6",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "978-0061120084",
    price: 14.99,
    description:
      "A powerful story about justice and empathy in the Deep South.",
    coverImage: "https://picsum.photos/seed/mockingbird/400/600",
    stockQuantity: 11,
    categories: ["Fiction", "History"],
    publisher: "Harper Perennial",
    publicationDate: "1960-07-11",
    rating: 4.8,
    reviews: [],
  },
  {
    id: "7",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbn: "978-0062316097",
    price: 22.99,
    description: "An engaging exploration of humanity’s past and future.",
    coverImage: "https://picsum.photos/seed/sapiens/400/600",
    stockQuantity: 20,
    categories: ["Non-Fiction", "History"],
    publisher: "Harper",
    publicationDate: "2015-02-10",
    rating: 4.8,
    reviews: [],
  },
  {
    id: "8",
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt & David Thomas",
    isbn: "978-0135957059",
    price: 49.99,
    description:
      "Timeless principles and practices for better software development.",
    coverImage: "https://picsum.photos/seed/pragmatic/400/600",
    stockQuantity: 6,
    categories: ["Technology", "Science"],
    publisher: "Addison-Wesley",
    publicationDate: "2019-09-13",
    rating: 4.8,
    reviews: [],
  },
  {
    id: "9",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    isbn: "978-0547928227",
    price: 12.49,
    description: "A classic fantasy adventure featuring Bilbo Baggins.",
    coverImage: "https://picsum.photos/seed/hobbit/400/600",
    stockQuantity: 18,
    categories: ["Fantasy", "Fiction"],
    publisher: "Mariner Books",
    publicationDate: "1937-09-21",
    rating: 4.8,
    reviews: [],
  },
  {
    id: "10",
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    isbn: "978-0756404741",
    price: 16.99,
    description: "A legendary tale of magic, music, and a gifted hero.",
    coverImage: "https://picsum.photos/seed/nameofthewind/400/600",
    stockQuantity: 9,
    categories: ["Fantasy", "Fiction"],
    publisher: "DAW",
    publicationDate: "2007-03-27",
    rating: 4.6,
    reviews: [],
  },
  {
    id: "11",
    title: "Dune",
    author: "Frank Herbert",
    isbn: "978-0441172719",
    price: 15.49,
    description:
      "Epic science fiction about power, prophecy, and a desert planet.",
    coverImage: "https://picsum.photos/seed/dune/400/600",
    stockQuantity: 13,
    categories: ["Science", "Fiction"],
    publisher: "Ace",
    publicationDate: "1965-08-01",
    rating: 4.7,
    reviews: [],
  },
  {
    id: "12",
    title: "The Martian",
    author: "Andy Weir",
    isbn: "978-0804139021",
    price: 14.25,
    description:
      "A stranded astronaut uses science and humor to survive on Mars.",
    coverImage: "https://picsum.photos/seed/martian/400/600",
    stockQuantity: 10,
    categories: ["Science", "Fiction"],
    publisher: "Crown",
    publicationDate: "2014-02-11",
    rating: 4.6,
    reviews: [],
  },
  {
    id: "13",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    isbn: "978-0374533557",
    price: 19.99,
    description: "A deep dive into how we think, decide, and make mistakes.",
    coverImage: "https://picsum.photos/seed/fastslow/400/600",
    stockQuantity: 16,
    categories: ["Non-Fiction", "Self-Help"],
    publisher: "Farrar, Straus and Giroux",
    publicationDate: "2011-10-25",
    rating: 4.6,
    reviews: [],
  },
  {
    id: "14",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    isbn: "978-0857197689",
    price: 17.5,
    description: "Timeless lessons on wealth, greed, and happiness.",
    coverImage: "https://picsum.photos/seed/psychmoney/400/600",
    stockQuantity: 22,
    categories: ["Non-Fiction", "Self-Help"],
    publisher: "Harriman House",
    publicationDate: "2020-09-08",
    rating: 4.7,
    reviews: [],
  },
  {
    id: "15",
    title: "Educated",
    author: "Tara Westover",
    isbn: "978-0399590504",
    price: 15.99,
    description: "A memoir about resilience, learning, and self-invention.",
    coverImage: "https://picsum.photos/seed/educated/400/600",
    stockQuantity: 12,
    categories: ["Biography", "Non-Fiction"],
    publisher: "Random House",
    publicationDate: "2018-02-20",
    rating: 4.7,
    reviews: [],
  },

  {
    id: "16",
    title: "Becoming",
    author: "Michelle Obama",
    isbn: "978-1524763138",
    price: 18.99,
    description: "An inspiring memoir about identity, family, and public life.",
    coverImage: "https://picsum.photos/seed/becoming/400/600",
    stockQuantity: 15,
    categories: ["Biography", "Non-Fiction"],
    publisher: "Crown",
    publicationDate: "2018-11-13",
    rating: 4.8,
    reviews: [],
  },
  {
    id: "17",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    isbn: "978-1250301697",
    price: 16,
    description: "A twisted psychological thriller with a shocking reveal.",
    coverImage: "https://picsum.photos/seed/silentpatient/400/600",
    stockQuantity: 7,
    categories: ["Mystery", "Fiction"],
    publisher: "Celadon Books",
    publicationDate: "2019-02-05",
    rating: 4.3,
    reviews: [],
  },
  {
    id: "18",
    title: "Gone Girl",
    author: "Gillian Flynn",
    isbn: "978-0307588371",
    price: 15.99,
    description: "A dark mystery about marriage, media, and manipulation.",
    coverImage: "https://picsum.photos/seed/gonegirl/400/600",
    stockQuantity: 9,
    categories: ["Mystery", "Fiction"],
    publisher: "Crown",
    publicationDate: "2012-06-05",
    rating: 4.2,
    reviews: [],
  },
  {
    id: "19",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "978-1503290563",
    price: 9.99,
    description: "A witty romance about manners, class, and misunderstandings.",
    coverImage: "https://picsum.photos/seed/prideprejudice/400/600",
    stockQuantity: 19,
    categories: ["Romance", "Fiction"],
    publisher: "Public Domain Classics",
    publicationDate: "1813-01-28",
    rating: 4.6,
    reviews: [],
  },
  {
    id: "20",
    title: "Me Before You",
    author: "Jojo Moyes",
    isbn: "978-0143124542",
    price: 13.5,
    description:
      "A heartfelt romance that challenges what it means to live fully.",
    coverImage: "https://picsum.photos/seed/mebeforeyou/400/600",
    stockQuantity: 8,
    categories: ["Romance", "Fiction"],
    publisher: "Penguin Books",
    publicationDate: "2012-01-05",
    rating: 4.4,
    reviews: [],
  },
  {
    id: "21",
    title: "Deep Work",
    author: "Cal Newport",
    isbn: "978-1455586691",
    price: 17.99,
    description: "Rules for focused success in a distracted world.",
    coverImage: "https://picsum.photos/seed/deepwork/400/600",
    stockQuantity: 21,
    categories: ["Self-Help", "Non-Fiction"],
    publisher: "Grand Central Publishing",
    publicationDate: "2016-01-05",
    rating: 4.6,
    reviews: [],
  },
  {
    id: "22",
    title: "The Power of Habit",
    author: "Charles Duhigg",
    isbn: "978-0812981605",
    price: 16.49,
    description: "How habits work and how to change them effectively.",
    coverImage: "https://picsum.photos/seed/powerhabit/400/600",
    stockQuantity: 17,
    categories: ["Self-Help", "Non-Fiction"],
    publisher: "Random House",
    publicationDate: "2012-02-28",
    rating: 4.5,
    reviews: [],
  },
  {
    id: "23",
    title: "The Lean Startup",
    author: "Eric Ries",
    isbn: "978-0307887894",
    price: 18,
    description: "Build products smarter with rapid experiments and learning.",
    coverImage: "https://picsum.photos/seed/leanstartup/400/600",
    stockQuantity: 10,
    categories: ["Technology", "Non-Fiction"],
    publisher: "Crown Business",
    publicationDate: "2011-09-13",
    rating: 4.4,
    reviews: [],
  },
  {
    id: "24",
    title: "Zero to One",
    author: "Peter Thiel",
    isbn: "978-0804139298",
    price: 16.99,
    description: "Notes on startups, innovation, and building the future.",
    coverImage: "https://picsum.photos/seed/zerotoone/400/600",
    stockQuantity: 12,
    categories: ["Technology", "Non-Fiction"],
    publisher: "Crown Business",
    publicationDate: "2014-09-16",
    rating: 4.3,
    reviews: [],
  },
  {
    id: "25",
    title: "The Innovators",
    author: "Walter Isaacson",
    isbn: "978-1476708690",
    price: 20.99,
    description:
      "A history of the pioneers who created the digital revolution.",
    coverImage: "https://picsum.photos/seed/innovators/400/600",
    stockQuantity: 9,
    categories: ["Technology", "Biography"],
    publisher: "Simon & Schuster",
    publicationDate: "2014-10-07",
    rating: 4.6,
    reviews: [],
  },
  {
    id: "26",
    title: "Steve Jobs",
    author: "Walter Isaacson",
    isbn: "978-1451648539",
    price: 19.49,
    description: "A definitive biography of Apple’s co-founder.",
    coverImage: "https://picsum.photos/seed/stevejobs/400/600",
    stockQuantity: 7,
    categories: ["Biography", "Technology"],
    publisher: "Simon & Schuster",
    publicationDate: "2011-10-24",
    rating: 4.7,
    reviews: [],
  },
  {
    id: "27",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "978-0553380163",
    price: 18.25,
    description: "Classic introduction to cosmology and the universe.",
    coverImage: "https://picsum.photos/seed/briefhistorytime/400/600",
    stockQuantity: 10,
    categories: ["Science", "Non-Fiction"],
    publisher: "Bantam",
    publicationDate: "1988-04-01",
    rating: 4.6,
    reviews: [],
  },
  {
    id: "28",
    title: "Cosmos",
    author: "Carl Sagan",
    isbn: "978-0345539434",
    price: 17.99,
    description: "A breathtaking journey through space and human discovery.",
    coverImage: "https://picsum.photos/seed/cosmos/400/600",
    stockQuantity: 13,
    categories: ["Science", "Non-Fiction"],
    publisher: "Ballantine Books",
    publicationDate: "1980-10-12",
    rating: 4.8,
    reviews: [],
  },
  {
    id: "29",
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    isbn: "978-1400052189",
    price: 16.99,
    description:
      "A true story at the intersection of science, ethics, and family.",
    coverImage: "https://picsum.photos/seed/henrietta/400/600",
    stockQuantity: 9,
    categories: ["Science", "Biography"],
    publisher: "Broadway Books",
    publicationDate: "2010-02-02",
    rating: 4.6,
    reviews: [],
  },
  {
    id: "30",
    title: "The Wright Brothers",
    author: "David McCullough",
    isbn: "978-1476728759",
    price: 15.99,
    description: "A vivid account of the brothers who invented flight.",
    coverImage: "https://picsum.photos/seed/wright/400/600",
    stockQuantity: 8,
    categories: ["History", "Biography"],
    publisher: "Simon & Schuster",
    publicationDate: "2015-05-05",
    rating: 4.5,
    reviews: [],
  },
];
